/*
 * ARX: Powerful Data Anonymization
 * Copyright (C) 2012 - 2014 Florian Kohlmayer, Fabian Prasser
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package org.deidentifier.arx.test;

import java.io.IOException;
import java.util.Arrays;
import java.util.Collection;

import org.deidentifier.arx.ARXConfiguration;
import org.deidentifier.arx.AttributeType.Hierarchy;
import org.deidentifier.arx.Data;
import org.deidentifier.arx.DataSubset;
import org.deidentifier.arx.criteria.DPresence;
import org.deidentifier.arx.criteria.HierarchicalDistanceTCloseness;
import org.deidentifier.arx.criteria.KAnonymity;
import org.deidentifier.arx.criteria.RecursiveCLDiversity;
import org.deidentifier.arx.metric.Metric;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

/**
 * Test for data transformations
 * 
 * @author Fabian Prasser
 * @author Florian Kohlmayer
 */
@RunWith(Parameterized.class)
public class TestAnonymizationCombinations extends TestAnonymizationAbstract {

    @Parameters(name = "{index}:[{0}]")
    public static Collection<Object[]> cases() throws IOException {
        return Arrays.asList(new Object[][] {
                /* 00*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 37223.24912482863d, new int[] { 1, 4, 1, 1, 1, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 35461.30001724414d, new int[] { 0, 2, 1, 2, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 42481.61974603207d, new int[] { 1, 4, 1, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))), "occupation", "../arx-data/data-junit/adult.csv", 398400.07418064494d, new int[] { 0, 4, 1, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)), "occupation", "../arx-data/data-junit/adult.csv", 324620.5269918695d, new int[] { 1, 1, 1, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 42481.61974603207d, new int[] { 1, 4, 1, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))), "occupation", "../arx-data/data-junit/adult.csv", 398400.07418064494d, new int[] { 0, 4, 1, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 39177.741183062324d, new int[] { 1, 4, 1, 1, 2, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)), "occupation", "../arx-data/data-junit/adult.csv", 324620.5269918695d, new int[] { 1, 1, 1, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 195829.0291224282d, new int[] { 5, 4, 1, 0, 1, 4, 4 }, false) },
                /* 10*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 195829.0291224282d, new int[] { 5, 4, 1, 0, 1, 3, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 195829.0291224282d, new int[] { 5, 4, 1, 0, 1, 3, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 2023751.2434216265d, new int[] { 4, 4, 1, 2, 1, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1961244.482255955d, new int[] { 4, 4, 1, 1, 1, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 195829.0291224282d, new int[] { 5, 4, 1, 0, 1, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 2023751.2434216265d, new int[] { 4, 4, 1, 2, 1, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 195829.0291224282d, new int[] { 5, 4, 1, 0, 1, 3, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1961244.482255955d, new int[] { 4, 4, 1, 1, 1, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 142414.2491462396d, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 121297.9782432488d, new int[] { 5, 2, 2, 0, 1, 2, 0 }, false) },
                /* 20*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 151844.67618589982d, new int[] { 2, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))), "istatenum", "../arx-data/data-junit/fars.csv", 1429434.0508910893d, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)), "istatenum", "../arx-data/data-junit/fars.csv", 1201007.0880104564d, new int[] { 0, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 151844.67618589982d, new int[] { 2, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))), "istatenum", "../arx-data/data-junit/fars.csv", 1429434.0508910893d, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 142414.2491462396d, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)), "istatenum", "../arx-data/data-junit/fars.csv", 1201007.0880104564d, new int[] { 0, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 400542.9546949437d, new int[] { 1, 0, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 400542.9546949437d, new int[] { 1, 0, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 574838.3678280929d, new int[] { 0, 5, 0, 2, 2, 2, 2, 2 }, false) },
                /* 30*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 5760138.103541854d, new int[] { 0, 5, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 3478926.4429797237d, new int[] { 0, 0, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 574838.3678280929d, new int[] { 0, 5, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 5760138.103541854d, new int[] { 0, 5, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 490137.690843512d, new int[] { 0, 4, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 4912828.240033204d, new int[] { 0, 4, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1287579.582154659d, new int[] { 0, 0, 0, 3, 4, 1, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1287579.582154659d, new int[] { 0, 0, 0, 3, 4, 1, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1589251.3824409053d, new int[] { 0, 0, 1, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", "../arx-data/data-junit/ihis.csv", 1.4719292081181683E7d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                /* 40*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)), "EDUC", "../arx-data/data-junit/ihis.csv", 9503511.261799559d, new int[] { 0, 0, 2, 3, 0, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1589251.3824409053d, new int[] { 0, 0, 1, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", "../arx-data/data-junit/ihis.csv", 1.4719292081181683E7d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1405067.4080803706d, new int[] { 0, 0, 1, 3, 4, 1, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.0d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)), "EDUC", "../arx-data/data-junit/ihis.csv", 1.2258628558792587E7d, new int[] { 0, 0, 0, 3, 3, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)), "occupation", "../arx-data/data-junit/adult.csv", 180132.40848244727d, new int[] { 0, 0, 1, 1, 2, 2, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1252060.0068011205d, new int[] { 2, 4, 1, 0, 0, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)), "istatenum", "../arx-data/data-junit/fars.csv", 560028.8197749632d, new int[] { 0, 0, 2, 3, 0, 0, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 1337026.0782033673d, new int[] { 0, 1, 0, 0, 0, 0, 1, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)), "EDUC", "../arx-data/data-junit/ihis.csv", 5823479.072286697d, new int[] { 0, 0, 0, 2, 0, 1, 0, 1 }, false) },
                /* 50*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 25247.843728346343d, new int[] { 1, 0, 1, 2, 2, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 40089.94234267562d, new int[] { 1, 4, 0, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))), "occupation", "../arx-data/data-junit/adult.csv", 367061.36913384416d, new int[] { 1, 4, 0, 0, 3, 1, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 28551.722291316088d, new int[] { 1, 0, 1, 2, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)), "occupation", "../arx-data/data-junit/adult.csv", 198181.40423329698d, new int[] { 1, 0, 1, 1, 2, 2, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 140991.28523275003d, new int[] { 3, 4, 0, 2, 0, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 166085.69686871197d, new int[] { 4, 4, 1, 2, 0, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1377036.0221522974d, new int[] { 2, 4, 1, 2, 0, 3, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 140991.28523275003d, new int[] { 3, 4, 0, 2, 0, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1202354.661834488d, new int[] { 2, 4, 1, 0, 0, 3, 1 }, false) },
                /* 60*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 88717.72875464808d, new int[] { 2, 0, 3, 3, 0, 0, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 121171.90731137781d, new int[] { 5, 2, 1, 1, 0, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))), "istatenum", "../arx-data/data-junit/fars.csv", 913268.7198249141d, new int[] { 2, 2, 1, 1, 0, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 91430.99721202679d, new int[] { 2, 0, 3, 3, 0, 1, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)), "istatenum", "../arx-data/data-junit/fars.csv", 585933.0095846696d, new int[] { 0, 2, 0, 1, 1, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 212656.0007008079d, new int[] { 0, 2, 0, 1, 1, 1, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 510614.55166065315d, new int[] { 0, 5, 0, 0, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 4970273.35942406d, new int[] { 1, 4, 0, 2, 2, 0, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 348418.92886372074d, new int[] { 0, 4, 0, 1, 2, 0, 1, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 3224480.4056847813d, new int[] { 0, 4, 0, 1, 2, 0, 0, 2 }, false) },
                /* 70*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 958639.1926385859d, new int[] { 0, 1, 2, 2, 0, 1, 1, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1471763.5565151938d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", "../arx-data/data-junit/ihis.csv", 1.4719292081181683E7d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1113232.2757912248d, new int[] { 0, 0, 1, 2, 3, 1, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)), "EDUC", "../arx-data/data-junit/ihis.csv", 7735322.29514608d, new int[] { 0, 0, 0, 1, 3, 0, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 25949.006866557105d, new int[] { 1, 0, 1, 2, 2, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 40282.237793276065d, new int[] { 1, 4, 0, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))), "occupation", "../arx-data/data-junit/adult.csv", 375361.4165541178d, new int[] { 1, 4, 0, 0, 3, 1, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 28759.66997058891d, new int[] { 1, 0, 1, 2, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("occupation", 4.0, 5)), "occupation", "../arx-data/data-junit/adult.csv", 209764.96161974446d, new int[] { 1, 0, 1, 1, 2, 2, 2, 0 }, false) },
                /* 80*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 143476.1692988251d, new int[] { 3, 4, 1, 1, 0, 3, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 167669.48564213671d, new int[] { 4, 4, 1, 2, 0, 3, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1407619.3716609066d, new int[] { 3, 4, 1, 0, 0, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 143476.1692988251d, new int[] { 3, 4, 1, 1, 0, 3, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("RAMNTALL", 4.0, 5)), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1254396.0338242168d, new int[] { 2, 4, 1, 0, 0, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 93329.75289569939d, new int[] { 2, 0, 3, 3, 0, 0, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 122965.09565112529d, new int[] { 5, 2, 1, 1, 0, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))), "istatenum", "../arx-data/data-junit/fars.csv", 958932.8909394158d, new int[] { 2, 2, 1, 1, 0, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 96001.27991005579d, new int[] { 2, 0, 3, 3, 0, 1, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("istatenum", 4.0, 5)), "istatenum", "../arx-data/data-junit/fars.csv", 630178.7565353527d, new int[] { 0, 2, 1, 1, 0, 2, 0 }, false) },
                /* 90*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 245635.2264706164d, new int[] { 0, 2, 0, 1, 1, 1, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 524320.6415885125d, new int[] { 0, 5, 0, 0, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 5108199.800500684d, new int[] { 1, 4, 0, 2, 2, 0, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 379027.9562797399d, new int[] { 0, 4, 0, 1, 2, 0, 1, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("Highest level of school completed", 4.0, 5)), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 3536911.5162082445d, new int[] { 0, 4, 0, 0, 2, 0, 1, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1028591.3561176283d, new int[] { 0, 1, 2, 2, 0, 1, 1, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1481940.8636253346d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new KAnonymity(5)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", "../arx-data/data-junit/ihis.csv", 1.4719292081181683E7d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1185607.5242246129d, new int[] { 0, 0, 1, 2, 3, 1, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new RecursiveCLDiversity("EDUC", 4.0, 5)), "EDUC", "../arx-data/data-junit/ihis.csv", 8460989.1661296d, new int[] { 0, 0, 0, 1, 3, 0, 0, 1 }, false) },
                /* 100*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 33649.91182261913d, new int[] { 1, 4, 1, 1, 0, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 40089.94234267562d, new int[] { 1, 4, 0, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))), "occupation", "../arx-data/data-junit/adult.csv", 367061.36913384416d, new int[] { 1, 4, 0, 0, 3, 1, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 188685.11376583856d, new int[] { 4, 4, 1, 1, 1, 4, 3 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 188685.11376583856d, new int[] { 4, 4, 1, 1, 1, 4, 3 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1377036.0221522974d, new int[] { 2, 4, 1, 2, 0, 3, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 130155.71991925791d, new int[] { 3, 2, 3, 0, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 142414.2491462396d, new int[] {1, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))), "istatenum", "../arx-data/data-junit/fars.csv", 913268.7198249141d, new int[] { 2, 2, 1, 1, 0, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 347941.726659357d, new int[] {0, 0, 0, 2, 2, 2, 2, 2 }, false) },
                /* 110*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 528157.4793996722d, new int[] { 0, 5, 0, 2, 2, 0, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 4970273.35942406d, new int[] { 1, 4, 0, 2, 2, 0, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1073722.7704188207d, new int[] { 0, 1, 1, 3, 0, 2, 1, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1471763.5565151938d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(true)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", "../arx-data/data-junit/ihis.csv", 1.4719292081181683E7d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 33660.30632776507d, new int[] { 1, 4, 1, 1, 0, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))), "occupation", "../arx-data/data-junit/adult.csv", 40282.237793276065d, new int[] { 1, 4, 0, 1, 3, 2, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("occupation", 0.2, Hierarchy.create("../arx-data/data-junit/adult_hierarchy_occupation.csv", ';'))), "occupation", "../arx-data/data-junit/adult.csv", 375361.4165541178d, new int[] { 1, 4, 0, 0, 3, 1, 2, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 188698.5209314101d, new int[] { 4, 4, 1, 1, 1, 4, 3 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 188714.66275887555d, new int[] { 4, 4, 1, 1, 1, 4, 3 }, false) },
                /* 120*/{ new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("RAMNTALL", 0.2, Hierarchy.create("../arx-data/data-junit/cup_hierarchy_RAMNTALL.csv", ';'))), "RAMNTALL", "../arx-data/data-junit/cup.csv", 1407619.3716609066d, new int[] { 3, 4, 1, 0, 0, 4, 4 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 130481.14757714343d, new int[] { 3, 2, 3, 0, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))), "istatenum", "../arx-data/data-junit/fars.csv", 142540.03759393407d, new int[] { 1, 2, 3, 3, 1, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("istatenum", 0.2, Hierarchy.create("../arx-data/data-junit/fars_hierarchy_istatenum.csv", ';'))), "istatenum", "../arx-data/data-junit/fars.csv", 958932.8909394158d, new int[] { 2, 2, 1, 1, 0, 2, 0 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 348509.59034915606d, new int[] { 0, 0, 0, 2, 2, 2, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 542366.1748035984d, new int[] { 0, 5, 0, 2, 2, 0, 2, 2}, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("Highest level of school completed", 0.2, Hierarchy.create("../arx-data/data-junit/atus_hierarchy_Highest level of school completed.csv", ';'))), "Highest level of school completed", "../arx-data/data-junit/atus.csv", 5108199.800500684d, new int[] { 1, 4, 0, 2, 2, 0, 2, 2 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1091154.3222191555d, new int[] {0, 1, 1, 3, 0, 2, 1, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))).addCriterion(new DPresence(0.05, 0.15, DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))), "EDUC", "../arx-data/data-junit/ihis.csv", 1481940.8636253346d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
                { new ARXAnonymizationTestCase(ARXConfiguration.create(0.05d, Metric.createEntropyMetric(false)).addCriterion(new HierarchicalDistanceTCloseness("EDUC", 0.2, Hierarchy.create("../arx-data/data-junit/ihis_hierarchy_EDUC.csv", ';'))), "EDUC", "../arx-data/data-junit/ihis.csv", 1.4719292081181683E7d, new int[] { 0, 0, 0, 3, 4, 2, 0, 1 }, false) },
        });
    }

    public TestAnonymizationCombinations(final ARXAnonymizationTestCase testCase) {
        super(testCase);
    }

}
