/*
 * ARX: Powerful Data Anonymization
 * Copyright (C) 2012 - 2014 Florian Kohlmayer, Fabian Prasser
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package org.deidentifier.arx.test;

import java.io.IOException;
import java.util.Arrays;
import java.util.Collection;

import org.deidentifier.arx.ARXConfiguration;
import org.deidentifier.arx.Data;
import org.deidentifier.arx.DataSubset;
import org.deidentifier.arx.criteria.DPresence;
import org.deidentifier.arx.metric.Metric;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

/**
 * Test for data transformations
 * 
 * @author Fabian Prasser
 * @author Florian Kohlmayer
 */
@RunWith(Parameterized.class)
public class TestAnonymizationDPresence extends TestAnonymizationAbstract {

    @Parameters(name = "{index}:[{0}]")
    public static Collection<Object[]> cases() throws IOException {
        return Arrays.asList(new Object[][] {

             /*00*/ { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",52.0d,new int[] {1, 4, 1, 1, 0, 2, 2, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",30238.20814844434d,new int[] {0, 1, 1, 2, 3, 2, 2, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",30238.20814844434d,new int[] {0, 1, 1, 2, 3, 2, 2, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",8.02127659574468d,new int[] {0, 0, 1, 2, 1, 2, 2, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",19804.28876750294d,new int[] {1, 0, 1, 1, 2, 2, 2, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",20747.36235040373d,new int[] {1, 0, 1, 1, 2, 2, 2, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",150.8d,new int[] {0, 4, 0, 1, 3, 2, 2, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",37223.24912482863d,new int[] {1, 4, 1, 1, 1, 2, 2, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",37223.24912482863d,new int[] {1, 4, 1, 1, 1, 2, 2, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",97.29032258064517d,new int[] {1, 4, 1, 1, 0, 2, 2, 1},false) },
             /*10*/ { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",33649.91182261913d,new int[] {1, 4, 1, 1, 0, 2, 2, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/adult.csv", ';'), Data.create("../arx-data/data-junit/adult_subset.csv", ';')))),"occupation","../arx-data/data-junit/adult.csv",33660.30632776507d,new int[] {1, 4, 1, 1, 0, 2, 2, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",186.58823529411765d,new int[] {5, 1, 1, 1, 1, 3, 4},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",183507.96668335146d,new int[] {5, 1, 1, 1, 1, 4, 4},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",183507.96668335146d,new int[] {5, 1, 1, 1, 1, 4, 4},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",6.375879396984924d,new int[] {4, 0, 1, 1, 1, 3, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",124388.37724603631d,new int[] {3, 2, 1, 1, 0, 2, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",128068.07605943352d,new int[] {2, 4, 1, 1, 0, 3, 4},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",906.2857142857143d,new int[] {5, 4, 1, 0, 1, 4, 4},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",195829.0291224282d,new int[] {5, 4, 1, 0, 1, 4, 4},false) },
             /*20*/ { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",195829.0291224282d,new int[] {5, 4, 1, 0, 1, 4, 4},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",333.89473684210526d,new int[] {4, 4, 1, 1, 1, 4, 3},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",188685.11376583856d,new int[] {4, 4, 1, 1, 1, 4, 3},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/cup.csv", ';'), Data.create("../arx-data/data-junit/cup_subset.csv", ';')))),"RAMNTALL","../arx-data/data-junit/cup.csv",188698.5209314101d,new int[] {4, 4, 1, 1, 1, 4, 3},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",53.402116402116405d,new int[] {3, 2, 3, 0, 1, 2, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",108403.75633342168d,new int[] {3, 2, 3, 0, 1, 2, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",108403.75633342168d,new int[] {3, 2, 3, 0, 1, 2, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",7.229942693409742d,new int[] {0, 2, 2, 3, 0, 1, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",64967.109244556275d,new int[] {1, 0, 3, 1, 0, 0, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",71702.44834529077d,new int[] {1, 0, 3, 1, 0, 0, 0},false) },
             /*30*/ { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",152.92424242424244d,new int[] {5, 2, 2, 0, 1, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",142414.2491462396d,new int[] {1, 2, 3, 3, 1, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",142414.2491462396d,new int[] {1, 2, 3, 3, 1, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",63.879746835443036d,new int[] {3, 2, 3, 0, 1, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",130155.71991925791d,new int[] {3, 2, 3, 0, 1, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/fars.csv", ';'), Data.create("../arx-data/data-junit/fars_subset.csv", ';')))),"istatenum","../arx-data/data-junit/fars.csv",130481.14757714343d,new int[] {3, 2, 3, 0, 1, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",81.70454545454545d,new int[] {0, 0, 0, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",347941.726659357d,new int[] {0, 0, 0, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",347941.726659357d,new int[] {0, 0, 0, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",12.388008270158512d,new int[] {0, 0, 0, 1, 1, 2, 2, 1},false) },
             /*40*/ { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",117237.8046569407d,new int[] {0, 1, 0, 1, 1, 0, 1, 0},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",159691.67833137428d,new int[] {0, 1, 0, 1, 1, 0, 1, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",162.42469879518072d,new int[] {0, 0, 1, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",400542.9546949437d,new int[] {1, 0, 0, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",400542.9546949437d,new int[] {1, 0, 0, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",82.07762557077625d,new int[] {0, 0, 0, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",347941.726659357d,new int[] {0, 0, 0, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/atus.csv", ';'), Data.create("../arx-data/data-junit/atus_subset.csv", ';')))),"Highest level of school completed","../arx-data/data-junit/atus.csv",348509.59034915606d,new int[] {0, 0, 0, 2, 2, 2, 2, 2},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",43.36845930232558d,new int[] {4, 0, 0, 3, 0, 2, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",1158549.730148498d,new int[] {5, 0, 0, 3, 0, 2, 0, 1},false) },
             /*50*/ { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",1158549.730148498d,new int[] {5, 0, 0, 3, 0, 2, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",6.0464055929885d,new int[] {0, 1, 0, 2, 0, 2, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",713446.6556131735d,new int[] {5, 0, 0, 0, 0, 1, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.0,0.2,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",799812.4275867805d,new int[] {4, 0, 0, 0, 0, 1, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",86.73691860465117d,new int[] {2, 0, 2, 3, 0, 2, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",1287579.582154659d,new int[] {0, 0, 0, 3, 4, 1, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.0d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",1287579.582154659d,new int[] {0, 0, 0, 3, 4, 1, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createAECSMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",27.411575562700964d,new int[] {0, 2, 1, 3, 0, 2, 0, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",1073722.7704188207d,new int[] {0, 1, 1, 3, 0, 2, 1, 1},false) },
             { new ARXTestCase(ARXConfiguration.create(0.05d,Metric.createNMEntropyMetric()).addCriterion(new DPresence(0.05,0.15,DataSubset.create(Data.create("../arx-data/data-junit/ihis.csv", ';'), Data.create("../arx-data/data-junit/ihis_subset.csv", ';')))),"EDUC","../arx-data/data-junit/ihis.csv",1091154.3222191555d,new int[] {0, 1, 1, 3, 0, 2, 1, 1},false) },

        });
    }

    public TestAnonymizationDPresence(final ARXTestCase testCase) {
        super(testCase);
    }

}
